### ISSUE TITLE
How to send tguser's media messages to tgbot. It can't work

### ISSUE THREAD

**Issue by pd5200** [AmarnathCJD/gogram#102]
if msg.Media() != nil {  
		// can work
		fmt.Println(h.client.SendMedia(msg.Peer, msg.Media(), &telegram.MediaOptions{
			Caption: msg.MessageText(),
		}))

		// no work
		if botclient != nil {
			fmt.Println(botclient.SendMedia(msg.Peer, msg.Media(), &telegram.MediaOptions{
				Caption: msg.MessageText(),
			}))
		}
		//Sendmsgto(botclient, msg.Peer, msg.Media(), msg.MessageText())
	}

	err:  <nil> sending MessagesSendMedia: [MEDIA_EMPTY] The provided media object is invalid. (code 400)

	geo ,sticker,and contact can worked,other no worked! help!

**Comment by AmarnathCJD** [comment]
media Is unique per account, you can reuse it's reference accross multiple accounts

To resend using botclient send to bot dm, then fetch it by listening to messages or get_messages by botclient  then send

**Comment by pd5200** [comment]
help me #113

**Comment by pd5200** [comment]
Does each type need to be downloaded locally and then uploaded to the server again? It seems that there are many types and there is no universal method.

**Comment by AmarnathCJD** [comment]
each type media is commonly interfaced to telegram.MessageMedia 

you can download it by calling m.Download()

to resent to another acc. you can either download and resent or send via the method i gave above.
