### ISSUE TITLE
CHAT_ID_INVALID 

### ISSUE THREAD

**Issue by pd5200** [AmarnathCJD/gogram#111]
func Test(client *telegram.Client, msg *telegram.NewMessage) {
	fmt.Println(msg.ChatID())
	fmt.Println(msg.Client.GetChat(msg.ChatID()))
}

//output
1811269222
<nil> sending MessagesGetChats: [CHAT_ID_INVALID] The provided chat id is invalid. (code 400)

//Why CHAT_ID_INVALID

**Comment by AmarnathCJD** [comment]
It maybe a superchat/channel, tried client.GetChannel?

**Comment by pd5200** [comment]
Why can't these methods be combined? Before, tdlib was combined, so I was a little unaccustomed.
