### ISSUE TITLE
 Is there no way to leave the basic group? 

### ISSUE THREAD

**Issue by pd5200** [AmarnathCJD/gogram#114]
Is there no way to leave the basic group? It only can leave supergroup and channel

func LeaveChat(client *telegram.Client, chatID int64) error {
	fmt.Println("LeaveChat", chatID)

	return client.LeaveChannel(chatID)

}

sending MessagesDeleteChatUser: [USER_ID_INVALID] The provided user ID is invalid. (code 400)

**Comment by AmarnathCJD** [comment]
client.MessagesDeleteChat() ?, these are raw api methods read their documentation

https://core.telegram.org/methods
