### ISSUE TITLE
How to delete different chat History？

### ISSUE THREAD

**Issue by pd5200** [AmarnathCJD/gogram#115]
func DeleteDialog(client *telegram.Client, chatID int64, justclear bool, revoke bool) error {
	fmt.Println("DeleteDialog", chatID, justclear, revoke)
	inputPeer, err := client.ResolvePeer(chatID) //转化
	if err != nil {
		comm.Logger.Warn("Failed to resolve peer:" + err.Error())
		return err
	}
	his, err := client.GetHistory(inputPeer, &telegram.HistoryOption{
		Limit:  1,
		Offset: 0,
	})
	if err != nil {
		comm.Logger.Warn("Failed to GetHistory :" + err.Error())
		return err
	}
	var maxid int32
	for _, msg := range his {
		maxid = msg.ID
	}
	_, err = client.MessagesDeleteHistory(&telegram.MessagesDeleteHistoryParams{
		JustClear: justclear,
		Revoke:    revoke,
		Peer:      inputPeer,
		MaxID:     maxid,
	})

	return err
}

It can only be work to the base group. How to work for a private or bot?

**Comment by AmarnathCJD** [comment]
client.MessagesDeleteHistory(&telegram.MessagesDeleteHistoryParams{

	})  with revoke as true? and id of private and maybe maxid=0
