### ISSUE TITLE
How to send a  contact ? thank you!

### ISSUE THREAD

**Issue by pd5200** [AmarnathCJD/gogram#116]
loc := telegram.InputGeoPointObj{
			Lat:            message.Location.Latitude,
			Long:           message.Location.Longitude,
			AccuracyRadius: 0,
		}
		motps := &telegram.MediaOptions{}
		_, err := tdlibc.SendMedia(chatid, loc, motps)
 
 

		contast := telegram.InputMediaContact{
			PhoneNumber: message.Contact.PhoneNumber,
			FirstName:   message.Contact.FirstName,
			LastName:    message.Contact.LastName,
		}
		motps := &telegram.MediaOptions{}
		_, err := tdlibc.SendMedia(chatid, contast, motps)   

///Both returned ： unknown media type

**Comment by jonneyless** [comment]
> ```
> 	loc := telegram.InputGeoPointObj{
> 		Lat:            message.Location.Latitude,
> 		Long:           message.Location.Longitude,
> 		AccuracyRadius: 0,
> 	}
> 	motps := &telegram.MediaOptions{}
> 	_, err := tdlibc.SendMedia(chatid, loc, motps)
> 
> 
> 
> 	contast := telegram.InputMediaContact{
> 		PhoneNumber: message.Contact.PhoneNumber,
> 		FirstName:   message.Contact.FirstName,
> 		LastName:    message.Contact.LastName,
> 	}
> 	motps := &telegram.MediaOptions{}
> 	_, err := tdlibc.SendMedia(chatid, contast, motps)   
> ```
> 
> ///Both returned ： unknown media type

	contast := &telegram.InputMediaContact{
		PhoneNumber: message.Contact.PhoneNumber,
		FirstName:   message.Contact.FirstName,
		LastName:    message.Contact.LastName,
	}
	motps := &telegram.MediaOptions{}
	_, err := tdlibc.SendMedia(chatid, contast, motps)

**Comment by jonneyless** [comment]
> ```
> 	loc := telegram.InputGeoPointObj{
> 		Lat:            message.Location.Latitude,
> 		Long:           message.Location.Longitude,
> 		AccuracyRadius: 0,
> 	}
> 	motps := &telegram.MediaOptions{}
> 	_, err := tdlibc.SendMedia(chatid, loc, motps)
> 
> 
> 
> 	contast := telegram.InputMediaContact{
> 		PhoneNumber: message.Contact.PhoneNumber,
> 		FirstName:   message.Contact.FirstName,
> 		LastName:    message.Contact.LastName,
> 	}
> 	motps := &telegram.MediaOptions{}
> 	_, err := tdlibc.SendMedia(chatid, contast, motps)   
> ```
> 
> ///Both returned ： unknown media type

https://github.com/AmarnathCJD/gogram/blob/fab347508c0602ab4502315a45ad964640c4640a/telegram/helpers.go#L503

**Comment by AmarnathCJD** [comment]
I'll take a look:)

**Comment by AmarnathCJD** [comment]
```go
contact := telegram.InputMediaContact{
		PhoneNumber: "1234567890",
		FirstName:   "John",
		LastName:    "Doe",
		Vcard:       "BEGIN:VCARD\nVERSION:3.0\nFN:John Doe\nTEL:1234567890\nEND:VCARD",
	}

fmt.Println(client.SendMedia("roseloverx", &cont))
```

working fine?

**Comment by AmarnathCJD** [comment]
reopen if still not working.

**Comment by pd5200** [comment]
working well
