### ISSUE TITLE
Compatibility of `fileID` in `UnpackBotFileID`

### ISSUE THREAD

**Issue by eos175** [AmarnathCJD/gogram#122]
Currently, the `UnpackBotFileID `function performs an XOR operation followed by an RLC, which is affecting compatibility with the old fileIDs. After conducting several experiments, no real benefit has been observed with this implementation. It is suggested to modify the [function](https://github.com/eos175/gogram/commit/8f9f66911acd9ffa85ed431c104bb1a20fc1d9e4) to maintain compatibility with the old fileIDs.

**Comment by AmarnathCJD** [comment]
done./
