### ISSUE TITLE
Proposal to Simplify Proxy Handling and CancelableReader Implementation

### ISSUE THREAD

**Issue by eos175** [AmarnathCJD/gogram#123]
Hello everyone,

I would like to propose an update to the gogram project regarding proxy handling and the implementation of `CancelableReader`.

**Proposal:**
Eliminate support for all proxy types except SOCKS5. This is because the other types do not provide significant benefits for our current use case. The recommendation is to use [Shadowsocks](https://shadowsocks.org/), which operates through SOCKS5.

**Technical Details:**
- We will use `golang.org/x/net/proxy`, which exposes a `Dial` interface.
- We plan to change the implementation of `CancelableReader` to simplify connection management and eliminate `panic`.

**Rationale:**
Currently, `CancelableReader` is used to cancel a TCP read using a context (`ctx`). However, this mechanism is primarily used when we want to stop the bot or exit the program. We can achieve the same result using `conn.Close()`, as when `conn.Read()` is being executed and `conn.Close()` is called, `Read()` will immediately return `net.ErrClosed`.

**Objective:**
The main objective of this change is to simplify the code and eliminate all `panic` calls, making the bot more robust and avoiding the need to run it through Docker or systemd to restart it in case of a `panic`.

I look forward to your comments and opinions on this proposal.

**Comment by AmarnathCJD** [comment]
The connection thing seems ok, doable

but what is wrong with the current impl. If proxies, isn't it good to support all 3 types of em.

**Comment by AmarnathCJD** [comment]
Have you found out the sources of panic

**Comment by eos175** [comment]
The connection is fine, what happens is that this error rarely occurs `AUTH_KEY_INVALID`:

```
[stderr] panic: [AUTH_KEY_INVALID] the auth key is invalid and needs to be reauthenticated (code -404)
[stderr]
[stderr] goroutine 4311 [running]:
[stderr] github.com/amarnathcjd/gogram.(*MTProto).startReadingResponses.func1()
[stderr]        /tmp/gogram/mtproto.go:520 +0xa99
[stderr] created by github.com/amarnathcjd/gogram.(*MTProto).startReadingResponses in goroutine 4339
[stderr]        /tmp/gogram/mtproto.go:465 +0x90
Command failed with error: exit status 2
Restarting process in 1 seconds...
```

I believe the source of the problem is Telegram or something beyond our control. However, what we can avoid is causing a panic.

**Comment by eos175** [comment]
> The connection thing seems ok, doable
> 
> but what is wrong with the current impl. Of proxies, isn't it good to support all 3 types of em.

In practice, http proxies are slow and their use is geared towards caching, reverse proxying... We should avoid using them for this type of application. That’s why we prefer socks5

**Comment by AmarnathCJD** [comment]
> The connection is fine, what happens is that this error rarely occurs `AUTH_KEY_INVALID`:
> 
> ```
> [stderr] panic: [AUTH_KEY_INVALID] the auth key is invalid and needs to be reauthenticated (code -404)
> [stderr]
> [stderr] goroutine 4311 [running]:
> [stderr] github.com/amarnathcjd/gogram.(*MTProto).startReadingResponses.func1()
> [stderr]        /tmp/gogram/mtproto.go:520 +0xa99
> [stderr] created by github.com/amarnathcjd/gogram.(*MTProto).startReadingResponses in goroutine 4339
> [stderr]        /tmp/gogram/mtproto.go:465 +0x90
> Command failed with error: exit status 2
> Restarting process in 1 seconds...
> ```
> 
> I believe the source of the problem is Telegram or something beyond our control. However, what we can avoid is causing a panic.

what if we reconnect on this.,? This issue never came for me tho.

**Comment by AmarnathCJD** [comment]
> The connection is fine, what happens is that this error rarely occurs `AUTH_KEY_INVALID`:
> 
> ```
> [stderr] panic: [AUTH_KEY_INVALID] the auth key is invalid and needs to be reauthenticated (code -404)
> [stderr]
> [stderr] goroutine 4311 [running]:
> [stderr] github.com/amarnathcjd/gogram.(*MTProto).startReadingResponses.func1()
> [stderr]        /tmp/gogram/mtproto.go:520 +0xa99
> [stderr] created by github.com/amarnathcjd/gogram.(*MTProto).startReadingResponses in goroutine 4339
> [stderr]        /tmp/gogram/mtproto.go:465 +0x90
> Command failed with error: exit status 2
> Restarting process in 1 seconds...
> ```
> 
> I believe the source of the problem is Telegram or something beyond our control. However, what we can avoid is causing a panic.

I'm sure it's related to session corruption, can you maybe save the session data on this panic and try to start from here.. like using client.ImportRawAuth maybe.

**Comment by eos175** [comment]
Why would the session become corrupted?

**Comment by AmarnathCJD** [comment]
any updates on this.?

**Comment by itrack** [comment]
Hello,
I encountered the same problem, it seems to be related to cache.

Thank you!

**Comment by AmarnathCJD** [comment]
> Hello, I encountered the same problem, it seems to be related to cache.
> 
> Thank you!
Could you elaborate.

**Comment by AmarnathCJD** [comment]
> Hello, I encountered the same problem, it seems to be related to cache.
> 
> Thank you!

.

**Comment by AmarnathCJD** [comment]
closing as incative

**Comment by itrack** [comment]
> closing as incative

Some people still sleep or have other things to do, so they are "inactive" for 18 hours 😅
DisableCache, if you set DisableCache to true, the problem disappears, before I did this the above problem appeared every time I closed the application after logging in.

**Comment by AmarnathCJD** [comment]
> > closing as incative
> 
> Hi, some people still sleep or have other things to do, so they are "inactive" for 18 hours 😅 DisableCache, if you set ClientConfig -> DisableCache to true, the problem disappears, before I did this, the above problem appeared every time I closed the application after logging in.

wydm everytime closed the application?

does the problem always happen? like always stuck? what's the behaviour after deleting cache.db
Are you on latest commit version.

**Comment by TAMILVIP007** [comment]
@itrack Stawp bullying my gurl

**Comment by eos175** [comment]
I haven't had much time to investigate, but it keeps happening randomly. Actually, the solution I proposed was to change the panics to errors and, in response, just perform a clean reconnection. I can work on this over the weekend

**Comment by AmarnathCJD** [comment]
> I haven't had much time to investigate, but it keeps happening randomly. Actually, the solution I proposed was to change the panics to errors and, in response, just perform a clean reconnection. I can work on this over the weekend

Alright, I'm tired of this lib 😹

**Comment by AmarnathCJD** [comment]
> @itrack Stawp bullying my gurl

nibbi show me your posyyy

**Comment by itrack** [comment]
> > > closing as incative
> > 
> > 
> > Hi, some people still sleep or have other things to do, so they are "inactive" for 18 hours 😅 DisableCache, if you set ClientConfig -> DisableCache to true, the problem disappears, before I did this, the above problem appeared every time I closed the application after logging in.
> 
> wydm everytime closed the application?
> 
> does the problem always happen? like always stuck? what's the behaviour after deleting cache.db Are you on latest commit version.

If I delete cache.db there are no more problems, seems to happen after first login -> stop application -> start again

**Comment by AmarnathCJD** [comment]
this is no longer happening right/

**Comment by TAMILVIP007** [comment]
@AmarnathCJD
