### ISSUE TITLE
NewMessage.Delete() doesn't have revoke parameter

### ISSUE THREAD

**Issue by TheKaram** [AmarnathCJD/gogram#125]
**Describe the bug**
`NewMessage.Delete()` doesn't have a `Revoke` parameter, so if you try to delete a message in private chat it will not be deleted for both parts and you have to use the longer method using `NewMessage.Client.DeleteMessages(NewMessage.ChatID(), []int32{NewMessage.ID}, true) `.

**To Reproduce**
Just try to delete message in a private chat using `NewMessage.Delete()`.

**Expected behavior**
Delete message in both parts by default as this is the most common use case or at least add `Revoke` parameter to `NewMessage.Delete()`.

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Version: 2.3.15

**Comment by AmarnathCJD** [comment]
Ok I'll add that

**Comment by TheKaram** [comment]
Thank you
