### ISSUE TITLE
Uploading is extremely slow

### ISSUE THREAD

**Issue by TheKaram** [AmarnathCJD/gogram#126]
**Describe the bug**
Uploading media is extremely slow to start, for a 170MB video i wait for 60 seconds and it didn't start the uploading process, i kept the code running for 2 minutes and the upload has not been finished. For example, in python using [pyrofork](https://github.com/Mayuri-Chan/pyrofork) it takes 9-13 seconds to upload the same file.

**To Reproduce**
Try upload a +100MB media file

**Expected behavior**
Upload process should be much faster than it is now (at least be in the same level of python).

**Desktop (please complete the following information):**
 - OS: ArchLinux and ubuntu arm
 - Version ubuntu 22.04

**Comment by AnjanaMadu** [comment]
@TheKaram Alrdy vroken vro. Cdj don't care

**Comment by AmarnathCJD** [comment]
> @TheKaram Alrdy vroken vro. Cdj don't care

bruh anju deer

**Comment by TheKaram** [comment]
sorry, but i didn't understand you

**Comment by AmarnathCJD** [comment]
your network speed?

**Comment by AmarnathCJD** [comment]
The issue is, sometimes parelell senders generation gets interrupted due to network drops, I have done such that as soon as a sender is made it starts participating in the upload cycle without waiting for entire senders to be made. I'll push that soon, try it out and say.

**Comment by TheKaram** [comment]
This is a speed test from server
![Screenshot_20240804-182157_Termius~3](https://github.com/user-attachments/assets/500d8ca9-5798-4448-9975-1023c603fe04)

**Comment by TheKaram** [comment]
> The issue is, sometimes parelell senders generation gets interrupted due to network drops, I have done such that as soon as a sender is made it starts participating in the upload cycle without waiting for entire senders to be made. I'll push that soon, try it out and say.

Ok, thank you for your great work.

**Comment by AmarnathCJD** [comment]
try now and feedback/

**Comment by TheKaram** [comment]
Wow, it's very fast now :fire:.

170MB video:
Gogram: 10.8s
Pyrofork: 12s
1.4GB video:
Gogram: 86s
Pyrofork: 82.5s

This small difference is a margin of error.
Thank you very much for this great work :zap:.
