### ISSUE TITLE
Videos uploaded from a subdirectory are not playable

### ISSUE THREAD

**Issue by dani3l0** [AmarnathCJD/gogram#127]
**Describe the bug**
Uploading large videos to a channel does not make them playable, they are treated as documents. To watch, I need to download them locally and then play with native video player.

Smaller (and shorter) videos work as expected, I can directly play them in my tg clients.

**To Reproduce**

1. Just upload some big video somewhere (channel in my case)

2. Code snippet I am using:
```
import (
	"myproject/config"

	tg "github.com/amarnathcjd/gogram/telegram"
)

var client *tg.Client

func main() {
	client, _ = tg.NewClient(tg.ClientConfig{
		AppID:   config.TelegramApiId,
		AppHash: config.TelegramApiHash,
	})

	client.ConnectBot(config.TelegramBotToken)

	// ChannelId is provided as int
	client.SendMedia(config.ChannelId, "./output.mp4", &tg.MediaOptions{
		Caption:       "*bold* _italic_ one two three",
		ParseMode:     "markdown",
	})
}
```

**Expected behavior**
Large, long videos are playable in Telegram clients.

**Screenshots**

This is a large MP4 video. Duration: 40 minutes. Can't be played directly in Telegram client.
![image](https://github.com/user-attachments/assets/475e7481-57cc-4091-8ebb-dccfa1021044)

This is a 9MB video. Duration: 40 seconds. **Works as expected.**
![image](https://github.com/user-attachments/assets/03b02f5e-6b83-4df3-929e-3315a0bd3938)

**Desktop:**
 - OS: Fedora Workstation 40, Golang from Fedora dnf repos (go1.22.5 linux/amd64)
 - Telegram client: Materialgram 5.2.1.1 flatpak
 - gogram v0.0.0-20240803081110-76b510013b18

**Additional context**

Tried also re-transcoding video with ffmpeg to various formats and repacking containers.
To be precise, I tried with transcoding to h264 (mp4 v1 and v2) and hevc. Unfortunately, neither helps.

**BTW, thanks for your great project!**

**Comment by AmarnathCJD** [comment]
![Screenshot 2024-08-05 005055](https://github.com/user-attachments/assets/b5968296-efc5-4b4c-8639-dab089ab6cb4)

working as expected from my side

can you send the mediainfo output of the file you are trying to send.?

**Comment by dani3l0** [comment]
Here it is:
```
General
ID                                       : 1 (0x1)
Complete name                            : KATOWICE  Pt. 2.08.2024r. W. Olszański, M. Osadowski NPTV.pl Rodacy Kamraci [6VNRAcrSR].mp4
Format                                   : MPEG-TS
File size                                : 871 MiB
Duration                                 : 2 h 49 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 720 kb/s
FileExtension_Invalid                    : ts m2t m2s m4t m4s tmf ts tp trp ty

Video
ID                                       : 257 (0x101)
Menu ID                                  : 1 (0x1)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 1 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 1 frame
Format settings, GOP                     : M=1, N=60
Codec ID                                 : 27
Duration                                 : 2 h 49 min
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Standard                                 : NTSC
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Color range                              : Limited
Color primaries                          : BT.601 PAL
Transfer characteristics                 : BT.601
Matrix coefficients                      : BT.601

Audio
ID                                       : 256 (0x100)
Menu ID                                  : 1 (0x1)
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Format version                           : Version 4
Muxing mode                              : ADTS
Codec ID                                 : 15-2
Duration                                 : 2 h 49 min
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 43 ms
```

And to give more background, it's a video downloaded from https://dlive.tv/ via `yt-dlp`

**Comment by AmarnathCJD** [comment]
Its maybe issue with telegram's video formats? 

for one file which uploaded as document i ran this
```
ffmpeg -hwaccel nvdec -i input.mp4 -vf "scale=w=1280:h=720:force_original_aspect_ratio=decrease" -c:v h264_nvenc -preset p1 -b:v 2000k -maxrate 2000k -bufsize 4000k -c:a aac -b:a 128k -movflags +faststart output.mp4
```

and got uploaded as video.
try and experiement, I think its not issue with lib

please update on this.

**Comment by dani3l0** [comment]
Not yet, I've been kinda busy today :<

Will let you know tomorrow

**Comment by dani3l0** [comment]
Okay, I guess I've discovered the real issue.
My observations were a bit misleading, actually it doesn't matter if a video is big or not.
For testing, I've been copying small videos to the same directory I run my project in, that's why they worked.

I think, **the pattern is when video file is served from a different directory**. Here's an updated code snippet:

```
package main

import (
	"myproject/config"

	tg "github.com/amarnathcjd/gogram/telegram"
)

var client *tg.Client

func main() {
	client, _ = tg.NewClient(tg.ClientConfig{
		AppID:   config.TelegramApiId,
		AppHash: config.TelegramApiHash,
	})

	client.ConnectBot(config.TelegramBotToken)

	// Serve video from a subdirectory
	client.SendMedia(config.ChannelId, "./downloads/output.mp4", &tg.MediaOptions{
		Caption:       "*bold* _italic_ one two three",
		ParseMode:     "markdown",
	})
}
```

Uploading video this way will result in this:
![image](https://github.com/user-attachments/assets/a48e8829-18e6-4631-8fa3-e178b2997b7e)


Still I'm not 100% sure, coz the problem may still be somewhere else. Please take a look :>

**Comment by RoseLoverX** [comment]
@dani3l0 maybe ffmpeg commands hardcoded only works for current directory.?

**Comment by dani3l0** [comment]
It has nothing to do with ffmpeg. Video formats are ok

**Comment by RoseLoverX** [comment]
@dani3l0 are the document attributes ok too.?

**Comment by dani3l0** [comment]
Must be. Video uploaded from current working dir is playable and everything is ok. Problem happens only when serving the file from different directory.

**Comment by RoseLoverX** [comment]
@dani3l0 thats so strange

**Comment by dani3l0** [comment]
Check the snippet.

**Comment by AmarnathCJD** [comment]
oh subdriectory or diffrent directory?

**Comment by dani3l0** [comment]
Both

**Comment by AmarnathCJD** [comment]
can you come @rosexchat .

**Comment by AmarnathCJD** [comment]
[
![Screenshot 2024-08-06 232142](https://github.com/user-attachments/assets/07b9b30b-d10f-4f5d-aad2-8cb3d79bf8b7)
](url)

from diff directory

**Comment by AmarnathCJD** [comment]
same for ./blah/bx/video_2024-08-06_21-32-07_339.mp4

**Comment by AmarnathCJD** [comment]
> Okay, I guess I've discovered the real issue. My observations were a bit misleading, actually it doesn't matter if a video is big or not. For testing, I've been copying small videos to the same directory I run my project in, that's why they worked.
> 
> I think, **the pattern is when video file is served from a different directory**. Here's an updated code snippet:
> 
> ```
> package main
> 
> import (
> 	"myproject/config"
> 
> 	tg "github.com/amarnathcjd/gogram/telegram"
> )
> 
> var client *tg.Client
> 
> func main() {
> 	client, _ = tg.NewClient(tg.ClientConfig{
> 		AppID:   config.TelegramApiId,
> 		AppHash: config.TelegramApiHash,
> 	})
> 
> 	client.ConnectBot(config.TelegramBotToken)
> 
> 	// Serve video from a subdirectory
> 	client.SendMedia(config.ChannelId, "./downloads/output.mp4", &tg.MediaOptions{
> 		Caption:       "*bold* _italic_ one two three",
> 		ParseMode:     "markdown",
> 	})
> }
> ```
> 
> Uploading video this way will result in this: ![image](https://private-user-images.githubusercontent.com/111448519/355547810-a48e8829-18e6-4631-8fa3-e178b2997b7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NjcwMTEsIm5iZiI6MTcyMjk2NjcxMSwicGF0aCI6Ii8xMTE0NDg1MTkvMzU1NTQ3ODEwLWE0OGU4ODI5LTE4ZTYtNDYzMS04ZmEzLWUxNzhiMjk5N2I3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxNzUxNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDdhOGRhYTJiYjJjMDA3YzQyMTgyNjQ0MDliYzkzNzllYmFmMzU5OTYyYTA5YWIxNGJlMDYxNTVjYTQ4NmU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YB8Iy_daUTL-o8jj6RmIHMZojN8JCAVh87tNdcxrDgE)
> 
> Still I'm not 100% sure, coz the problem may be somewhere else. Please take a look :>

I think the output.mp4 might be incomplete? can u share the exact file in some place?

**Comment by AmarnathCJD** [comment]
even tried videos from https://dlive.tv/p/loupdi+XCGWSkXIg

**Comment by dani3l0** [comment]
Okay, something reeeally weird is happening here:
If the output.mp4 file is incomplete, then why is it working when uploaded from working dir? wtf

I'll do further investigation and update on this

Anyways, **there's a workaround by creating a symlink in working dir**

**Comment by eos175** [comment]
use `filepath.Abs()`

**Comment by AmarnathCJD** [comment]
> use `filepath.Abs()`

irrelevent ig, file path exists, gets uploaded

**Comment by dani3l0** [comment]
I've played tday a bit with my project on a work pc with OpenSUSE Tumbleweed, with the same Go version. Now, even the symlink workaround doesn't work. Must be sth wrong on my side.

ig it's a hwaccel or codec issue, as mentioned earlier (also I have very poorly configured hwaccel on this pc)

If I finally get this to work, I'll update xd

**Comment by AmarnathCJD** [comment]
so its not an issue with the lib? :

**Comment by dani3l0** [comment]
dunno. I tested other videos as well and some of them were working properly, some of them got sent as documents. Finally, idk where the problem is.

**Comment by AmarnathCJD** [comment]
> dunno. I tested other videos as well and some of them were working properly, some of them got sent as documents. Finally, idk where the problem is.

did you test with another client for eg-: telethon (python)

**Comment by dani3l0** [comment]
nope, I will do it now

**Comment by dani3l0** [comment]
Telethon is ok

**Comment by AmarnathCJD** [comment]
Wow, ok, your system is Linux right Ill try out.

**Comment by eos175** [comment]
> Wow, ok, your system is Linux right Ill try out.

Why would the OS affect it?

**Comment by AmarnathCJD** [comment]
> > Wow, ok, your system is Linux right Ill try out.
> 
> Why would the OS affect it?

If the same code works in win, then why not.

**Comment by eos175** [comment]
I don't understand how the same video would cause something to change. It must be something else. Could you share a zip file of the project to try to reproduce the issue?

**Comment by dani3l0** [comment]
Tried to reproduce with an example code, but weird things keeps happening. On sample, one-file code video gets preview correctly. Must be a mistake somewhere in my project. 

Sauce code to my project is [here](https://github.com/dani3l0/nptw) (made it public temporarily). You don't have to put ur own video, just set `debug_mode: true` in config.yml file and the whole _problematic_ process will begin.

Oh, make sure u upload video from cache dir, this is when the issue happens.

**Comment by AmarnathCJD** [comment]
Found the issue; how about now/

**Comment by dani3l0** [comment]
Seems like it's working flawlessly now :tada:

Thanks, good job :+1:
