### ISSUE TITLE
client.AddDeleteHandler  bug?

### ISSUE THREAD

**Issue by pd5200** [AmarnathCJD/gogram#132]
client.AddDeleteHandler(telegram.OnDeleteMessage, handler.Delete)

This returns:
type DeleteMessage struct {
    Client    *Client
    ChannelID int64
    Messages  []int32
}

Deleting personal chat records will trigger the handler, but `ChannelID` is `0`, so it is impossible to know which chat the message was deleted from.

Deleting messages in groups and channels does not trigger the handler.

So, there might be an issue with this function. Could you provide an example to demonstrate the correct usage?

When deleting messages in a group or channel with your own account, the handler is triggered. However, when other people in the same group delete messages for everyone, the handler is not triggered. In private chats, deleting messages on both sides triggers the handler, but there is no way to obtain the chat ID, only the message ID can be obtained.

**Comment by AmarnathCJD** [comment]
delete updates are not reliably sent by telegram afaik.

**Comment by AmarnathCJD** [comment]
> client.AddDeleteHandler(telegram.OnDeleteMessage, handler.Delete)
> 
> This returns: type DeleteMessage struct { Client *Client ChannelID int64 Messages []int32 }
> 
> Deleting personal chat records will trigger the handler, but `ChannelID` is `0`, so it is impossible to know which chat the message was deleted from.
> 
> Deleting messages in groups and channels does not trigger the handler.
> 
> So, there might be an issue with this function. Could you provide an example to demonstrate the correct usage?
> 
> When deleting messages in a group or channel with your own account, the handler is triggered. However, when other people in the same group delete messages for everyone, the handler is not triggered. In private chats, deleting messages on both sides triggers the handler, but there is no way to obtain the chat ID, only the message ID can be obtained.

on deletion of private chat messages telegram sends UpdateDeleteMessages

which only has the message id field since the ids are shared accross all private chats, only way to get which chat it is to keep a local cache implementation 


also **bots** don't recieve reliable delete updates.

if any delete update comes the handle will be triggered.
