### ISSUE TITLE
maybe something wrong on  *telegram.NewMessage   

### ISSUE THREAD

**Issue by pd5200** [AmarnathCJD/gogram#138]
func (h *BotHandler) AnyMsg(msg *telegram.NewMessage) error {
 
	fmt.Printf("msg.Sender.Self: %t, msg.Sender.ID %d msg.Message.FromID %d, msg.ChatID() %d, msg.Message.GroupedID %d msg.Message.ViaBotID %d\n", msg.Sender.Self, msg.Sender.ID, msg.Message.FromID, msg.ChatID(), msg.Message.GroupedID, msg.Message.ViaBotID)

	}
	msg.Sender.Self: false, msg.Sender.ID XXX6666 msg.Message.FromID &{XXX6666}, msg.ChatID() XXX6666, msg.Message.GroupedID 0 msg.Message.ViaBotID 0

When I send a message through my own Telegram account to another user, if it's in a private chat window, it displays as above. However, what I expect to see is:

	msg.Sender.Self: true, msg.Sender.ID selfidxxxx msg.Message.FromID &{selfidxxxx}, msg.ChatID() XXX6666, msg.Message.GroupedID 0 msg.Message.ViaBotID 0

	 	github.com/amarnathcjd/gogram v0.0.0-20240803081110-76b510013b18

**Comment by RoseLoverX** [comment]
@pd5200 W sonoflars?
