### ISSUE TITLE
Proposal to update `ProgressCallback` to use bytes

### ISSUE THREAD

**Issue by eos175** [AmarnathCJD/gogram#139]
I propose changing the `ProgressCallback` to `func(totalBytes, downloadedBytes int)` instead of `func(totalPart, downloadedPart int)`. This change will allow for more precise tracking of progress in bytes.

**Comment by eos175** [comment]
although it would be better to use `func(totalBytes, downloadedBytes int) error` to handle errors and cancel the upload or download if needed

**Comment by AmarnathCJD** [comment]
mm

**Comment by AmarnathCJD** [comment]
> although it would be better to use `func(totalBytes, downloadedBytes int) error` to handle errors and cancel the upload or download if needed

meh bad idea, its multi goroutined so if we cancel the state would be uncertain.
