### ISSUE TITLE
Cannot cast [channel_ID] to any kind of InputPeer

### ISSUE THREAD

**Issue by rtcq** [AmarnathCJD/gogram#14]
```go
peerID := -1001187973481 // Already checked it's correct
_, err := client.GetInputPeer(int64(peerID))
if err != nil {
panic(err)
}
```
```
panic: cannot cast -1001187973481 to any kind of InputPeer
```

**Comment by AmarnathCJD** [comment]
@rtcq The chat/channel is not yet in cache
To get InputPeer the accesshash of channel should be recived in IncomingUpdates and saved cache

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by rtcq** [comment]
I see, so when I want to get a message, what would be the best method to get it directly? my current method is requesting it with channel_ID and message_ID like `client.GetMessages(channelID, &telegram.SearchOption{IDs: messageID})` but the availability of the `channelID` is not guaranteed. Is there any one-time unique identifier for a message to get it from both public and private channels by the client?

**Comment by AmarnathCJD** [comment]
> I see, so when I want to get a message, what would be the best method to get it directly? my current method is requesting it with channel_ID and message_ID like `client.GetMessages(channelID, &telegram.SearchOption{IDs: messageID})` but the availability of the `channelID` is not guaranteed. Is there any one-time unique identifier for a message to get it from both public and private channels by the client?

If the channel has a username
inputpeer, _ := client.GetSendablePeer("username")

if it's private, wait for NewMessage event and save the chatID and AccessHash from it. Reuse these values in future.

**Comment by rtcq** [comment]
Ok thanks
