### ISSUE TITLE
Parallel sessions being merged

### ISSUE THREAD

**Issue by jmancool65** [AmarnathCJD/gogram#145]
Im not really sure if this is a bug but when I try and launch several clients at the same time on separate go routines only one tcp connection actually ends up being active? I am trying to monitor activity across several channels and chats and ideally would like to have several clients running with my credentials.

**To Reproduce**
1. Run several clients at once and you will notice only one tcp connection is actually active.

**Expected behavior**
I would like to have several independent tcp connections running at once.

**Comment by AmarnathCJD** [comment]
Already Lemme see if that's the case

**Comment by AmarnathCJD** [comment]
![Screenshot 2024-09-02 212200](https://github.com/user-attachments/assets/01cec80d-45ff-44ab-ba4a-d078a49ac70e)

its a new connection for each clients
https://github.com/AmarnathCJD/gogram/blob/115c4df667ee9304ffcd3ca21bf6003ac3e9d869/internal/transport/transport.go#L30

**Comment by jmancool65** [comment]
Interesting I notice that in your logs it is showing that you are connecting to different datacenters. Even when specifying a datacenter number in my config all of my clients seem to be connecting to the same address The reason my initial intution was that only one tcp connection was alive is because both clients that I am running are monitoring the same chat with the same handler function but from my console it looks like the message is only being processed once. Can you show me how you are setting up your client config? Maybe I am missing something.  
<img width="819" alt="Screenshot 2024-09-02 at 11 28 18 AM" src="https://github.com/user-attachments/assets/62caf70a-a818-4b77-a5ec-16c1e8f50139">
:
<img width="698" alt="Screenshot 2024-09-02 at 11 26 13 AM" src="https://github.com/user-attachments/assets/41767b22-0b35-4fd8-a569-472515c6f850">

**Comment by AmarnathCJD** [comment]
![image](https://github.com/user-attachments/assets/dbb79c69-6ecc-42c0-adda-0518acf8db49)

also there is no effect in setting datacenter in config, every account is linked with a dc on creation and it cant be changed

**Comment by jmancool65** [comment]
Ok that makes sense. In your earlier screenshots are you using two separate bot tokens ? I am still a bit confused as to why If I start two clients I only get updates for one.

**Comment by AmarnathCJD** [comment]
> Ok that makes sense. In your earlier screenshots are you using two separate bot tokens ? I am still a bit confused as to why If I start two clients I only get updates for one.
Yes seperate tokens 

You using same botTokens?

**Comment by jmancool65** [comment]
Yes I am using the same user token across concurrent sessions. Is this not possible ?

**Comment by AmarnathCJD** [comment]
It's possible, but an update would only be recieved in any of the session, not all afaik.
