### ISSUE TITLE
How to obtain the number of SendDice dice points?

### ISSUE THREAD

**Issue by xianyurich** [AmarnathCJD/gogram#148]
How to obtain the number of SendDice dice points?

**Comment by AnjanaMadu** [comment]
@xianyurich log into telegram app and see. solution by @Tamilvip007

**Comment by AmarnathCJD** [comment]
> How to obtain the number of SendDice dice points?

Lemme see

**Comment by AmarnathCJD** [comment]
> How to obtain the number of SendDice dice points?

```go
msg, _ := client.SendDice("roseloverx", "🎲")
fmt.Println(msg.Media().(*telegram.MessageMediaDice).Value)
```
