### ISSUE TITLE
Panic nil dereference when message comes from supergroup and when you try to send in supergroup 

### ISSUE THREAD

**Issue by robertt3kuk** [AmarnathCJD/gogram#149]
**Describe the bug**

**To Reproduce**
1. ```	message.MarkRead()
	peer := &tg.PeerChat{ChatID: forwardingGroup}
	content := fmt.Sprintf("Message forwarded from user @%s\n (ID: tg://user?id=%d)\n in chat %s (ID: %d) \n content: %s",
		message.Sender.Username, message.Sender.ID, message.Chat.Title, message.ChatID(), message.Text())

	_, err := message.Client.SendMessage(peer, content)
	if err != nil {
		log.Printf("Error sending forwarded message: %v", err)
		return err
	}
	_, err = message.Client.Forward(
		peer,
		message.Sender.ID,
		[]int32{message.ID},
	)
	if err != nil {
		log.Printf("Error forwarding message: %v", err)
		return err
	```

**Expected behavior**
to send it 

**Screenshots**
<img width="990" alt="image" src="https://github.com/user-attachments/assets/5877af69-3781-40ba-8ca6-c45636e6e671">



**Additional context**
What i find interesting is that it happens when i try to access message.Chat entity in this case it fails for example if i don't send the message.ChatID or message.Chat.Title it won't happen, also i can't send to the supergroups by id because it says invalid id from telegram part but still when i try to debug and log.Println(message.PeerID) it prints out the id is the same im sending for example as forwarding group

**Comment by robertt3kuk** [comment]
<img width="986" alt="image" src="https://github.com/user-attachments/assets/3bf1ac96-2f26-40be-a9be-3acd6544447d">
here is additional when i try to message.MarkRead() i printed out the error what it shows in supergroup as far im concered when i try to print out the type of Peer it says it's Chat

**Comment by AmarnathCJD** [comment]
Ok Thanks for the details, I'll take a Look

**Comment by AmarnathCJD** [comment]
In here the message.chat was probably nil, creating the panic, check for these nils. I have pushed like to set the title of sender as chat title in case the chat was nil
