### ISSUE TITLE
SessionLoader cannot be used

### ISSUE THREAD

**Issue by wind-hx** [AmarnathCJD/gogram#15]
SessionLoader is an internal module and I cannot use

**Comment by AmarnathCJD** [comment]
What are you trying to achieve with session Loader??

**Comment by wind-hx** [comment]
My session is stored in redis, and I need to implement the load and store methods by myself

**Comment by wind-hx** [comment]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/17685971/212802911-3b878cd9-a99b-4d17-adc6-948df8a90a36.png">

I need to convert the session data stored in redis into a session object available in gogram

**Comment by AmarnathCJD** [comment]
"1B" + "auth_key" + "::" + "authkey_hash" + "::" + "ip_addr" + "::" + "dc_id"

encode it to urlsafe base64 and pass as StringSession as a workaround

Will make the method public soon .

**Comment by AmarnathCJD** [comment]
Fixed this

**Comment by TAMILVIP007** [comment]
@AmarnathCJD ok vai
