### ISSUE TITLE
High CPu usage while file download.?

### ISSUE THREAD

**Issue by AmarnathCJD** [AmarnathCJD/gogram#154]

**Comment by krau** [comment]
I noticed this problem.

The [downloadPart](https://github.com/AmarnathCJD/gogram/blob/f3775b93a5a39a52ca2dcfa82ca2cd84e510cb87/telegram/media.go#L480) func  launches too many goroutines at the same time and use busy waiting to get an avaliable woker, which leads to high CPU usage.

**Comment by AmarnathCJD** [comment]
> I noticed this problem.
> 
> The [downloadPart](https://github.com/AmarnathCJD/gogram/blob/f3775b93a5a39a52ca2dcfa82ca2cd84e510cb87/telegram/media.go#L480) func launches too many goroutines at the same time and use busy waiting to get an avaliable woker, which leads to high CPU usage.

Soln?

**Comment by AmarnathCJD** [comment]
#Fixed
