### ISSUE TITLE
Fail to to get channel info with GetChannel 

### ISSUE THREAD

**Issue by 3axap-4** [AmarnathCJD/gogram#159]
**Describe the bug**
I have added a folder with collection of a channels for my Telegram account. I'm trying to read throug information about the channels from that folder. For some of the channels I'm getting an error while trying to perform `GetChannel` method call - "no channel with id ******** or missing from cache"

**To Reproduce**
```
client, err := telegram.NewClient(telegram.ClientConfig{
    AppID: appId, AppHash: appHash,
})

if err != nil {
    log.Fatal(err)
}

client.Conn()

client.Login("phone number")

dialogs, err := client.MessagesGetDialogFilters()
if err != nil {
    log.Fatal("Fail to get folders %v", err)
}

for _, f := range dialogs{
  switch t := f.(type) {
    case *telegram.DialogFilterChatlist:
	HandleFolder(client, t)
    default:
	log.Printf("Unsupported directory type found %T", t)
  }
}


. . . . .

func HandleFolder(client *telegram.Client, folder *telegram.DialogFilterChatlist) {
    for _, p := range folder.IncludePeers {
        chId := p.(*telegram.InputPeerChannel).ChannelID
	ch, err := client.GetChannel(chId)
- - - - >>> Error happen here
		
. . . . . . .

```

**Expected behavior**
A channel information successfully retreived.
Current behavior: There is no peer with id 2222222222 or missing from cache

**Comment by RoseLoverX** [comment]
@3axap-4 Ok duely noted

**Comment by AmarnathCJD** [comment]
> **Describe the bug** I have added a folder with collection of a channels for my Telegram account. I'm trying to read throug information about the channels from that folder. For some of the channels I'm getting an error while trying to perform `GetChannel` method call - "no channel with id ******** or missing from cache"
> 
> **To Reproduce**
> 
> ```
> client, err := telegram.NewClient(telegram.ClientConfig{
>     AppID: appId, AppHash: appHash,
> })
> 
> if err != nil {
>     log.Fatal(err)
> }
> 
> client.Conn()
> 
> client.Login("phone number")
> 
> dialogs, err := client.MessagesGetDialogFilters()
> if err != nil {
>     log.Fatal("Fail to get folders %v", err)
> }
> 
> for _, f := range dialogs{
>   switch t := f.(type) {
>     case *telegram.DialogFilterChatlist:
> 	HandleFolder(client, t)
>     default:
> 	log.Printf("Unsupported directory type found %T", t)
>   }
> }
> 
> 
> . . . . .
> 
> func HandleFolder(client *telegram.Client, folder *telegram.DialogFilterChatlist) {
>     for _, p := range folder.IncludePeers {
>         chId := p.(*telegram.InputPeerChannel).ChannelID
> 	ch, err := client.GetChannel(chId)
> - - - - >>> Error happen here
> 		
> . . . . . . .
> ```
> 
> **Expected behavior** A channel information successfully retreived. Current behavior: There is no peer with id 2222222222 or missing from cache

If you call client.MessagesGetDialogFilters() peers won't be auto added to cache, there is chat and useri lists along with the dialogs so fetch accesshasesh from there
