### ISSUE TITLE
mtproto error code 4294966892 unhandled

### ISSUE THREAD

**Issue by wind-hx** [AmarnathCJD/gogram#16]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/17685971/212846496-d6e357f1-6afc-4c81-96fc-0c26ae545679.png">

When some error codes appear, there is no need to reconnect. Reconnecting will not solve the problem, but will lead to infinite reconnection

**Comment by itzrexmodz** [comment]
@wind-hx Ok

**Comment by AmarnathCJD** [comment]
Is this code mentioned somewhere in mtproto docs?
Error never occurdd to me

**Comment by AmarnathCJD** [comment]
So it's like AuthKeyNot found error

Will check..
