### ISSUE TITLE
Every time I log in, an error message appears after a few hours.

### ISSUE THREAD

**Issue by crispony** [AmarnathCJD/gogram#160]
![QQ20241022-073858](https://github.com/user-attachments/assets/0919dc08-e16e-44b0-a260-24fb62d6416b)

**Comment by AmarnathCJD** [comment]
does the bot stop responding?

**Comment by crispony** [comment]
Keeps reconnecting and then can't connect

**Comment by AmarnathCJD** [comment]
Logs of that .?
