### ISSUE TITLE
panic when try to get info about the chat or chat message sender when switch group type from private to public 

### ISSUE THREAD

**Issue by robertt3kuk** [AmarnathCJD/gogram#163]
**Describe the bug**
trouble with groups which were private then become public 

**To Reproduce**
 Go to 'create private group and after few messages make it public how i believe under the hood changes group type which i request in my previous issue and make is it like nil but the chat id is printed when i print out '

**Expected behavior**
it should give back the chat object or at least should get the title all i want is title and also can't get user info who sent in this type of group 
`
chat id 7209924601
time="2024-11-16T12:30:18Z" level=error msg="Error getting chat info: sending MessagesGetChats: [CHAT_ID_INVALID] The provided chat id is invalid. (code 400)"
2024/11/16 12:30:18 [panic] gogram [client] - runtime error: invalid memory address or nil pointer dereference`
here is the chat id 

code example is `	chat ,err:= b.user.GetChat(message.ChatID())
`
but also when you try to get the title by message.Chat.Title it also sends nothing but when i did when it was private group it was okay so you have trouble with this type of group i think it's supergroups 

**Additional context**

**Comment by robertt3kuk** [comment]
`content := b.constructMessageContent(sender, message, message.Chat.Title)`
this way too it sends nothing

**Comment by robertt3kuk** [comment]
its my own method to make content for forwarding i have question how do i know that it's channel type not just group without getting the panic

**Comment by robertt3kuk** [comment]
and also was wondering how to clean the cache regularly ?

**Comment by AmarnathCJD** [comment]
> its my own method to make content for forwarding i have question how do i know that it's channel type not just group without getting the panic

type casting m.Message.PeerID or checking if m.CHannel is nil or m.Chat is nil

**Comment by AmarnathCJD** [comment]
> and also was wondering how to clean the cache regularly ?

client.Cache.InputPeers

there is no method for it, but this fields are accesible

**Comment by AmarnathCJD** [comment]
> and also was wondering how to clean the cache regularly ?

client.Cache.Clear()
