### ISSUE TITLE
-404, see if its issue with dc ipaddresses diffreing from whats returned on helpGetConfig (yet to verify)

### ISSUE THREAD

**Issue by AmarnathCJD** [AmarnathCJD/gogram#171]

**Comment by AmarnathCJD** [comment]
@chiggajith

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by AmarnathCJD** [comment]
> ![image](https://private-user-images.githubusercontent.com/99405899/397436225-019faf0a-e20b-421e-8c66-634e8023bcca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MjQ5ODEsIm5iZiI6MTczNDYyNDY4MSwicGF0aCI6Ii85OTQwNTg5OS8zOTc0MzYyMjUtMDE5ZmFmMGEtZTIwYi00MjFlLThjNjYtNjM0ZTgwMjNiY2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE2MTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMGEyZmE0M2NiOTkwOWViYWQ4YzdlYzhkMGJjYTg0NmIxN2U2ZjkxMzM3OGUzNjU1NDBhYmU2ODM2MWM3NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wDVFbm87jm0BWD4DhqroJSV2c-q8WVXizdqokGC2GJc)
> 
> Is this related to this snippet?

Yes yes

**Comment by RoseLoverX** [comment]
@proper-gentleman Is it happening to you ??

**Comment by proper-gentleman** [comment]
Yes, could it be happening if I'm logged into the same account with 2 different IPs?

**Comment by AmarnathCJD** [comment]
Fixed.
