### ISSUE TITLE
First login, session error (Windows Only)

### ISSUE THREAD

**Issue by EniMusguera** [AmarnathCJD/gogram#2]
First login, session was not found. Default auth code in examples. Output:
\session.session: The system cannot find the file specified.

How can i fix it ?

**Comment by TAMILVIP007** [comment]
@EniMusguera You sure you are on updated version? Check ur gogram version and update it. If still error sahre your error log with your codes

**Comment by anonyindian** [comment]
@EniMusguera A

**Comment by AmarnathCJD** [comment]
@TAMILVIP007 Lmao

**Comment by AmarnathCJD** [comment]
> First login, session was not found. Default auth code in examples. Output: \session.session: The system cannot find the file specified.
> 
> How can i fix it ?

Its should be fixed in latest version. Replaced Paths with filepath.Join()

**Comment by AmarnathCJD** [comment]
[https://github.com/AmarnathCJD/gogram/commit/21ecd43ff6247a79c5fc20bfc7a4375b65b9092f#diff-09afad5e9ef39edcc10fed4b442121d5592ed430be81edf580aea3c7cdb6ae1b](Commit)

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by AmarnathCJD** [comment]
@TAMILVIP007

**Comment by TAMILVIP007** [comment]
@AmarnathCJD
