### ISSUE TITLE
LogDebug rip

### ISSUE THREAD

**Issue by TAMILVIP007** [AmarnathCJD/gogram#22]
```client, _ = telegram.TelegramClient(telegram.ClientConfig{
		AppID:    int(variables.Envs.APP_ID),
		AppHash:  variables.Envs.APP_HASH,
		LogLevel: telegram.LogDebug,
	})
```

LogDebug deosnt seem to do anything still logs are logges as info

**Comment by AmarnathCJD** [comment]
info < debug so info displays on debug, havnt added much debug logging

**Comment by itzrexmodz** [comment]
@AmarnathCJD

**Comment by AmarnathCJD** [comment]
> @AmarnathCJD 

Lamde nonhorny

**Comment by TAMILVIP007** [comment]
> info < debug so info displays on debug, havnt added much debug logging

thats gay

**Comment by AmarnathCJD** [comment]
@TAMILVIP007 Like you
