### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by stdkhai** [AmarnathCJD/gogram#23]
https://github.com/AmarnathCJD/gogram/blob/ee7d323872bda8803ad017c442354f69da200181/internal/session/string.go#L66

Index 5 out of range (length=5), change to:
`AppID = int32(Sep[4][0])`

**Comment by TAMILVIP007** [comment]
@stdkhai

**Comment by AmarnathCJD** [comment]
@stdkhai ah okhee
