### ISSUE TITLE
hi，Is there a layer132 version of the code，please

### ISSUE THREAD

**Issue by ashkiynn** [AmarnathCJD/gogram#24]

**Comment by AmarnathCJD** [comment]
@ashkiynn It can be generated using https://github.com/AmarnathCJD/gogram/tree/master/internal/cmd/tlgen

**Comment by ashkiynn** [comment]
Thank you very much

**Comment by TAMILVIP007** [comment]
@ashkiynn Why do you need tho

**Comment by ashkiynn** [comment]
@TAMILVIP007 I was involved in a project similar to telegrom server side，now start preparing for the stress test，test draws on gogram.but I used layer6132 and modified 6132, interspersed with some custom content, including 6133、6145 and my own creation

**Comment by TAMILVIP007** [comment]
@ashkiynn Oh okiee

**Comment by ashkiynn** [comment]
@AmarnathCJD
Sorry to bother you again. I used cmd/tlgen, but created methods_gen.go have '*tl.bool', how to solve, old file is 'bool'

**Comment by AmarnathCJD** [comment]
@ashkiynn Replace  all *tl.bool with bool, i forgot to edit it 😐

**Comment by ashkiynn** [comment]
Very happy, I can already log in and send messages
But how do I receive messages from others?
I know I can go through `get updates` to actively get the message, is it possible to actively receive message push from the server?

**Comment by AmarnathCJD** [comment]
@ashkiynn func u(i any) bool {
 ..... Updates
}

client.AddCustomServiceRequestHandler(u)



this sends all incoming updates to the function in realtime

**Comment by AmarnathCJD** [comment]
@ashkiynn Or you can add event handlers like

client.AddMessageHandler('/start', func (m *telegram.NewMessage) error {
 fmt.Println(m)
 return nil
})

**Comment by ashkiynn** [comment]
@AmarnathCJD think you again, I'll try it tomorrow.
