### ISSUE TITLE
Nil pointer

### ISSUE THREAD

**Issue by stdkhai** [AmarnathCJD/gogram#26]
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6e0e80]

goroutine 160117 [running]:
github.com/amarnathcjd/gogram.(*MTProto).sendPacket(0xc0000c58c0, {0x995720?, 0xc000865d20?}, {0x0, 0x0, 0x0})
        /pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20230210125721-738ac3048af7/network.go:59 +0x3c0
github.com/amarnathcjd/gogram.(*MTProto).InvokeRequestWithoutUpdate(0xc0000c58c0?, {0x995720?, 0xc000865d20?}, {0x0?, 0x0?, 0x2?})
        /pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20230210125721-738ac3048af7/mtproto.go:312 +0x28
github.com/amarnathcjd/gogram.(*MTProto).Reconnect(0xc0000c58c0, 0x0)
        /pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20230210125721-738ac3048af7/mtproto.go:351 +0x158
github.com/amarnathcjd/gogram.(*MTProto).processResponse(0xc0000c58c0, {0x9a3690, 0xc000140690})
        /pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20230210125721-738ac3048af7/mtproto.go:483 +0x3b9
github.com/amarnathcjd/gogram.(*MTProto).readMsg(0xc0000c58c0)
        /pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20230210125721-738ac3048af7/mtproto.go:446 +0x1b1
github.com/amarnathcjd/gogram.(*MTProto).startReadingResponses.func1()
        /pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20230210125721-738ac3048af7/mtproto.go:378 +0xcb
created by github.com/amarnathcjd/gogram.(*MTProto).startReadingResponses
        /pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20230210125721-738ac3048af7/mtproto.go:367 +0xaa
`

https://github.com/AmarnathCJD/gogram/blob/738ac3048af7d475aa172531b0906ca06a79734a/network.go#L59

**Comment by AmarnathCJD** [comment]
Is this the nil object?
