### ISSUE TITLE
AuthImportBotAuthorization:

### ISSUE THREAD

**Issue by TAMILVIP007** [AmarnathCJD/gogram#37]
2023/03/14 23:16:34 sending AuthImportBotAuthorization: Can't make request. Connection is not established

**Comment by anonyindian** [comment]
@TAMILVIP007 sync your device time and try again

**Comment by AmarnathCJD** [comment]
@TAMILVIP007 Hein

**Comment by AmarnathCJD** [comment]
Irreverent
