### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by Terminal1337** [AmarnathCJD/gogram#41]
create a well described documentation please like telethon and pyrogram or madeline proto in php

**Comment by AmarnathCJD** [comment]
@Terminal1337 Ok will be soon up on gogram.readthedocs.io

**Comment by AmarnathCJD** [comment]
gogramd.vercel.app

**Comment by TAMILVIP007** [comment]
@AmarnathCJD smd

**Comment by AmarnathCJD** [comment]
> @AmarnathCJD smd

No
