### ISSUE TITLE
Some bugs, Peer bot

### ISSUE THREAD

**Issue by npdkdev** [AmarnathCJD/gogram#42]
**I have some problems**

The first problem, I don't know what the problem is, I have pictures 1 and 2
![IMG_20230511_063633_973](https://github.com/AmarnathCJD/gogram/assets/49522880/757abff8-2583-433d-9eb2-dcb49966b60d)
![IMG_20230511_063630_920](https://github.com/AmarnathCJD/gogram/assets/49522880/9bc94872-2165-4188-a6a4-789ab89b6ad6)
When the program is run and displayed like the first picture, the bot does not run and does not respond, but when it appears like the second picture, the bot runs normally

The second problem is that the bot is already running, I try to send a chat to the user who has communicated with the bot, the results are normal, but when I kill the program with `**Ctrl + c**`, then try to send a chat with the user, I get an error ` peer no user with id 6281818110 or missing from cache`, I am confused about how it works until it can be like that, is it true that as a bot you have to save the peer, I think the bot can interact forever when it is /start and not blocked by the user.

then I tried to use `EnableCache: true `
the problem is solved but a new problem like this appears `Error while moving temporary file to cache file: rename /tmp/cache-1348554052.tmp cache.journal: invalid cross-device link` worse I can not do interrupt or **Ctrl + c** so every time I want to stop the program I have to `**Ctrl + z**` then run `kill -9 pid` very tiring, this problem does not always occur, but if it happens I have to receive chat or interaction from users in order to send chat to them again.
![IMG_20230511_064828_141](https://github.com/AmarnathCJD/gogram/assets/49522880/e273d2d2-4755-4e40-babc-a2b048050788)

**Comment by AmarnathCJD** [comment]
Ok noted
The first issue i would need to see the code

2nd issue cache file is not yet stable it hangs the main program sometimes so disabled it by default and the current cache file implementation seems broken I will fix it

Also a SIGTERM kill will be added

**Comment by npdkdev** [comment]
First problem,
the code is like the example [echobot.go](https://github.com/AmarnathCJD/gogram/blob/2.0/examples/bot/echobot.go#L32)
on that line I added fmt.Println("BOT STARTED")
when the bot runs normally `BOT STARTED` will also appear in the terminal, if the bot does not respond `BOT STARTED` does not appear

is it possible to use session storage like SQLite, is cache one of the better options, or maybe add both of them

**Comment by RoseLoverX** [comment]
> First problem, the code is like the example [echobot.go](https://github.com/AmarnathCJD/gogram/blob/2.0/examples/bot/echobot.go#L32) on that line I added fmt.Println("BOT STARTED") when the bot runs normally `BOT STARTED` will also appear in the terminal, if the bot does not respond `BOT STARTED` does not appear
> 
> is it possible to use session storage like SQLite, is cache one of the better options, or maybe add both of them

sometimes it doesnt respond mean your internet is not stable maybe

added Client.Cache.ImportJSON function now you can implement any custom sql or another cache
fixed cache file bug

**Comment by npdkdev** [comment]
Client.Cache.ImportJSON  Is this already automatic or does it need to be added, and does it have to be ExportJSON before the program is stopped?
