### ISSUE TITLE
Update layer scheme

### ISSUE THREAD

**Issue by npdkdev** [AmarnathCJD/gogram#44]
Can you you update api layer, because I cannot login as user, the error is **panic: sending AuthSentCode: [UPDATE_APP_LOGIN] this layer no longer supports logging in, please update your app (code 406)**, maybe can you tell me how to update the layer, I will update it

**Comment by AmarnathCJD** [comment]
@npdkdev Okey 👌,  need to work on updating parser first then 🥲

**Comment by AmarnathCJD** [comment]
@npdkdev Yeah I'm having trouble understandimg it cuz it breaks the current parser the 2.0 flag puts empty bytes and i couldn't find the order :(

**Comment by npdkdev** [comment]
I foolishly tried to change the parser, I tried and got `*_gen.go` then moved it into `telegram/` and changed the Api in `const.go` to `158`, after trying it I only get the log `connection to [...] - <TCPFull>` and no further response :(

**Comment by AmarnathCJD** [comment]
@npdkdev Yeah the internal decoder breaks which hangs the program

**Comment by AmarnathCJD** [comment]
@AmarnathCJD https://github.com/AmarnathCJD/gogram/blob/2.0/internal/encoding/tl/decoder.go >>

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by AnjanaMadu** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AnjanaMadu

**Comment by TAMILVIP007** [comment]
@TAMILVIP007

**Comment by TAMILVIP007** [comment]
@TAMILVIP007

**Comment by TAMILVIP007** [comment]
@TAMILVIP007

**Comment by AnjanaMadu** [comment]
@TAMILVIP007

**Comment by AnjanaMadu** [comment]
@TAMILVIP007

**Comment by AnjanaMadu** [comment]
@TAMILVIP007

**Comment by AmarnathCJD** [comment]
> Can you you update api layer, because I cannot login as user, the error is **panic: sending AuthSentCode: [UPDATE_APP_LOGIN] this layer no longer supports logging in, please update your app (code 406)**, maybe can you tell me how to update the layer, I will update it

Strange I'm not getting this error
And am suucessfully able to login and send auth code etc...
Check the lib version etc

**Comment by npdkdev** [comment]
I found the problem, I am using `AppID=1` and `AppHash` which belongs to telegram iOS, I have tried to replace it with my own obtained from my.telegram.org and it works, but is it not possible to update to the latest layer 158, if the problem is with the parser is it possible to recreate it using methods and layouts like [gotd](https://github.com/gotd/td), maybe using [gotd/tl](https://github.com/gotd/tl)

**Comment by AmarnathCJD** [comment]
@npdkdev Nope the structures are different and gotd codes are so huge I can't even finish reading them

I need external help to complete the parser 🙂

**Comment by AmarnathCJD** [comment]
#8
