### ISSUE TITLE
DownloadMedia function downloads only 512kb of file

### ISSUE THREAD

**Issue by AnjanaMadu** [AmarnathCJD/gogram#45]
I would like to report a bug in the `DownloadMedia` function of gogram, the Telegram MTProto library. Currently, the function is not functioning as expected, as it only downloads a maximum of 512kb of the file instead of the entire file.

Expected Behavior:
When utilizing the `DownloadMedia` function, I anticipate that it will download the complete file without any limitations on the file size.

Actual Behavior:
However, the function seems to be limited to downloading only 512kb of the file, regardless of the file's actual size. This behavior prevents users from retrieving the complete file content.

Steps to Reproduce:
To reproduce the issue, follow these steps:
1. Initialize the gogram library and establish a connection to the Telegram API.
2. Use the `DownloadMedia` function to download a file larger than 512kb.
3. Observe that the function only retrieves 512kb of the file, leaving the remaining content inaccessible.

Expected Output:
The `DownloadMedia` function should be able to download the entire file, regardless of its size. Users should be able to retrieve the complete content of the requested media.

Additional Information:
- Version of gogram library: idk
- Operating System: Windows 10 Pro 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)

This issue significantly affects users who rely on the `DownloadMedia` function to retrieve files from Telegram. It would be greatly appreciated if the bug could be addressed, allowing for seamless downloading of files of any size.

Please let me know if any further information or clarification is needed.

**Comment by AnjanaMadu** [comment]
@AnjanaMadu @RoseLoverX Hi

**Comment by TAMILVIP007** [comment]
@AnjanaMadu

**Comment by TAMILVIP007** [comment]
@AnjanaMadu bby smd

**Comment by AmarnathCJD** [comment]
@AnjanaMadu Omfg will take a look

**Comment by TAMILVIP007** [comment]
@AnjanaMadu

**Comment by RoseLoverX** [comment]
@AnjanaMadu Ok noted

**Comment by AnjanaMadu** [comment]
Bro has finally fixed the problem. Appreciate it!!
