### ISSUE TITLE
Bad Guidance in readme

### ISSUE THREAD

**Issue by TAMILVIP007** [AmarnathCJD/gogram#49]
**Bug Description**

A specific method mentioned in the [gogram](https://github.com/AmarnathCJD/gogram) library's README file is missing in the codebase, causing functional inconsistencies.

**To Reproduce**

1. Access the [relevant section of the README file](https://github.com/AmarnathCJD/gogram/blob/84be75d00aa54c6e309fcad62ea93ab990c49012/README.rst?plain=1#L112).
2. Scroll down and review the provided code snippet.
3. Notice that the expected method is not present in the library codebase.

**Expected Behavior**

The expected behavior is for the mentioned method to be available in the `gogram` library, aligning with the documentation provided in the README file.

**Screenshots**

If applicable, please attach screenshots or code snippets that help illustrate the issue.

**Desktop (Brave - Linux)**

- Operating System: Linux
- Browser: Brave
- Version: [e.g., Latest Version]

**Additional Context**

Additional information regarding the problem:

The method mentioned in the README file is crucial for performing a specific task in the gogram library. However, upon examining the codebase, it is evident that the method is missing, leading to inconsistencies in the library's functionality.

To further understand the issue, I reviewed the provided code snippet in the README file and attempted to locate the corresponding method in the gogram library's source code. Unfortunately, the method is absent, which contradicts the documentation's claim.

This missing method affects the ability to achieve the desired functionality, hampering the intended use of the gogram library in real-world scenarios. As a result, developers relying on this method are unable to leverage its capabilities as described in the README file.

Attached below is an example of the code snippet from the README file, indicating the missing method:

Providing the complete and accurate implementation of the missing method would greatly benefit developers using the gogram library, as it would enable them to leverage the desired functionality seamlessly.

Please let me know if any additional information or clarification is required to address this issue effectively.

**Comment by AmarnathCJD** [comment]
@TAMILVIP007 what method?

**Comment by TAMILVIP007** [comment]
@AmarnathCJD GetParticipant

**Comment by AmarnathCJD** [comment]
@TAMILVIP007 acha thats GetChatMember

**Comment by TAMILVIP007** [comment]
@AmarnathCJD Acha Then BAd guidence in readme

**Comment by AmarnathCJD** [comment]
@TAMILVIP007 No spoon feeding use common sense

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
jnl

**Comment by AmarnathCJD** [comment]
@TAMILVIP007 What

**Comment by TAMILVIP007** [comment]
@AmarnathCJD jnl

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by itzrexmodz** [comment]
@TAMILVIP007 [bro] you [stoopid] asl

**Comment by AnjanaMadu** [comment]
@itzrexmodz 💀

**Comment by TAMILVIP007** [comment]
@AnjanaMadu Jnl lund

**Comment by TAMILVIP007** [comment]
@itzrexmodz Jnl lund

**Comment by TAMILVIP007** [comment]
@itzrexmodz

**Comment by TAMILVIP007** [comment]
@TAMILVIP007
