### ISSUE TITLE
Inconsistant type handling

### ISSUE THREAD

**Issue by TAMILVIP007** [AmarnathCJD/gogram#50]
<h2>Describe the bug</h2>
<p>A clear and concise description of what the bug is.</p>

<h2>Code Information</h2>
<pre><code>func StreamFile(m *telegram.NewMessage) error {
	if m.Args() == "" || !m.IsReply() || !m.Message.ReplyTo.
		m.Reply("No file link found. Use &lt;code&gt;/stream filelink&lt;/code&gt; command to stream the file from the link or reply to a video file to stream it.")
		return nil
	}
	fmt.Println(filelink)
	return nil
}</code></pre>

<h2>To Reproduce</h2>
<p>Steps to reproduce the behavior:</p>
<ol>
  <li>Go to '...'</li>
  <li>Click on '...'</li>
  <li>Scroll down to '...'</li>
  <li>See the error related to the type not being properly handled after <code>ReplyToMsg</code> in the <a href="https://github.com/AmarnathCJD/gogram">AmarnathCJD/gogram</a> library.</li>
</ol>

<h2>Expected behavior</h2>
<p>A clear and concise description of what you expected to happen.</p>
<p>The expected behavior is that the <code>ReplyToMsg</code> method in the <a href="https://github.com/AmarnathCJD/gogram">AmarnathCJD/gogram</a> library should properly handle and display all fields of the replied message. This includes fields beyond the <code>ReplyToMsg</code> ID, such as sender information, message content, timestamp, and any other relevant data associated with the replied message.</p>

<h2>Observed behavior</h2>
<p>A clear and concise description of what is currently happening.</p>
<p>The current behavior is that after using the <code>ReplyToMsg</code> method, only the <code>ReplyToMsg</code> ID is displayed. Other fields and data associated with the replied message, such as sender information and message content, are not properly handled and displayed. This inconsistency in handling the type after <code>ReplyToMsg</code> limits the ability to access and utilize the complete information of the replied message.</p>

<h2>Screenshots</h2>
<p>If applicable, add screenshots to help explain your problem.</p>
<p><img src="https://graph.org/file/153d7c7bde3ca6000b196.jpg" alt="Screenshot of the type handling issue after ReplyToMsg"></p>

<h2>Desktop</h2>
<ul>
  <li>OS: Linux</li>
  <li>Browser: Safari (latest version)</li>
</ul>

<h2>Additional context</h2>
<p>Add any other context about the problem here.</p>
<p>This issue affects the functionality and usability of the <a href="https://github.com/AmarnathCJD/gogram">AmarnathCJD/gogram</a> library as it prevents users from accessing and utilizing the complete set of fields and data associated with the replied message. It is essential for the library to handle the type properly after <code>ReplyToMsg</code> to ensure consistent behavior and provide access to all relevant information of the replied message.</p>

**Comment by AmarnathCJD** [comment]
It's how telegram sends the update in mtproto. Unlike BotAPI, Telegram doesn't send the entire replied message object together with the update, which can be inefficient in certain cases. However, if you do need to obtain the complete replied message object, you can simply call the `m.GetReplyMessage()` function. This function allows you to retrieve the full replied message object when necessary.

**Comment by TAMILVIP007** [comment]
@AmarnathCJD Acha then MTP gei

**Comment by TAMILVIP007** [comment]
@TAMILVIP007 Lawde it misguides all who reads readme

**Comment by AmarnathCJD** [comment]
https://github.com/AmarnathCJD/gogram/issues/50#issuecomment-1614062820
