### ISSUE TITLE
add Callback function in Login

### ISSUE THREAD

**Issue by Esiarp8** [AmarnathCJD/gogram#51]
`type Callback func() (string, error)

func (c *Client) Login(phoneNumber string, callback Callback, options ...*LoginOptions) (bool, error) {
	// ......

	if opts.Code == "" {
		hash, e := c.SendCode(phoneNumber)
		if e != nil {
			return false, e
		}
		opts.CodeHash = hash
		for {
			// use call back to get code  Phone code
			codeInput, err := callback()
			if err != nil {
				return false, err
			}

			// ......
		}
	        for {
		        // use call back to get password  Two-steps verification
		       passwordInput, err := callback()
			if err != nil {
				return false, err
			}
	        }
	}

	// ......
}
`
I'm using the ui form to log in, could add a callback to send a code so I can interact with the ui?

**Comment by AmarnathCJD** [comment]
@Esiarp8 So like func() string {}?

**Comment by Esiarp8** [comment]
Wow , You're so quick reply is really fast haha
func (c *Client) Login(phoneNumber string, callback Callback, options ... *LoginOptions) (bool, error)
When I added the ui I realized it was all command line input
fmt.Printf("Enter code: ")
var codeInput string
fmt.Scanln(&codeInput)

fmt.Printf("Enter password: ")
var passwordInput string
fmt.Scanln(&passwordInput)
I would like to add the callback function so that I can use it in the ui to reply haha

func getCodeFromUser() (string, error) {
	// Pop up a window here to receive the verification code entered by the user
	// Then return this verification code
}

func main() {
	client := // Create your client
	phoneNumber := // Your phone number
	client.Login(phoneNumber, getCodeFromUser)
}

**Comment by AmarnathCJD** [comment]
:) Telegram notifications 

Lemme take a look

**Comment by AmarnathCJD** [comment]
Can you test out the code Pushed

**Comment by Esiarp8** [comment]
> Can you test out the code Pushed @Esiarp8

I'll give it a try haha

**Comment by Esiarp8** [comment]
@AmarnathCJD 
type LoginOptions struct {
	Password         string `json:"password,omitempty"`
	Code             string `json:"code,omitempty"`
	CodeHash         string `json:"code_hash,omitempty"`
	CodeCallback     func() (string, error)
	PasswordCallback func() (string, error)
	FirstName        string `json:"first_name,omitempty"`
	LastName         string `json:"last_name,omitempty"`
}

I just noticed that
RoseLoverX adding code to client.Login and 2FApassword callbacks
made the additions.
It has solved my problem, thanks so much.

**Comment by itzrexmodz** [comment]
@AmarnathCJD Good night Sleep well

**Comment by TAMILVIP007** [comment]
@Esiarp8 jnl

**Comment by TAMILVIP007** [comment]
@itzrexmodz acha

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@Esiarp8 do you mind joining t.me/RoseXChat

**Comment by Esiarp8** [comment]
> @Esiarp8 do you mind joining t.me/RoseXChat

Just joined haha

**Comment by TAMILVIP007** [comment]
@Esiarp8

**Comment by TAMILVIP007** [comment]
@Esiarp8 parry
