### ISSUE TITLE
how to get the names or ids of all channels

### ISSUE THREAD

**Issue by Esiarp8** [AmarnathCJD/gogram#52]
hello, just a question, after logging in, how to get the names or ids of all channels
I can't seem to find a way to do that.

**Comment by AmarnathCJD** [comment]
@Esiarp8 If using user account then, GetDialogs

**Comment by AmarnathCJD** [comment]
@AmarnathCJD client.GetDialogs

**Comment by Esiarp8** [comment]
> @Esiarp8 If using user account then, GetDialogs

GetDialogs gets all the user's dialogs, this includes the user's personal chats, groups and channels. can then iterate through these dialogs to find the ones that are of type channel and finally get the channel ID or name from these channel dialogs？

**Comment by AmarnathCJD** [comment]
@Esiarp8 Yes returns dialogs has a .Chats[] field having all the chats and channels, if tl.ChannelObj{} it is channel

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by Esiarp8** [comment]
> @Esiarp8 Yes returns dialogs has a .Chats[] field having all the chats and channels, if tl.ChannelObj{} it is channel



> @Esiarp8 Yes returns dialogs has a .Chats[] field having all the chats and channels, if tl.ChannelObj{} it is channel

hi is there any examples? My attempts don't seem to be working haha
