### ISSUE TITLE
How to get the title of ChatID and the title of ChannelID

### ISSUE THREAD

**Issue by Esiarp8** [AmarnathCJD/gogram#55]
Hello, with
ChatID
ChannelID
How can I get the title, that is the chat name

**Comment by AmarnathCJD** [comment]
@Esiarp8 U can only get it if it's present in library cache

**Comment by AmarnathCJD** [comment]
@AmarnathCJD client.GetChannel(id)

**Comment by Esiarp8** [comment]
> @AmarnathCJD client.GetChannel(id)

thank you haha
