### ISSUE TITLE
Fix downloadMedia.

### ISSUE THREAD

**Issue by AnjanaMadu** [AmarnathCJD/gogram#56]
`Dev already knows the bug. This issue for just pinging him`

**Comment by AmarnathCJD** [comment]
@AnjanaMadu Ok ping received:) will start working soon

**Comment by AnjanaMadu** [comment]
@AmarnathCJD 16,740,000ms

**Comment by AmarnathCJD** [comment]
@AnjanaMadu That is normal with Jio

**Comment by AmarnathCJD** [comment]
Will fix tommorow EOD :)

**Comment by itzrexmodz** [comment]
@AmarnathCJD ok

**Comment by AnjanaMadu** [comment]
Okii oni-chan~ (｡♥‿♥｡)

**Comment by TAMILVIP007** [comment]
@AnjanaMadu Bc

**Comment by AnjanaMadu** [comment]
> Will fix tommorow EOD :)

when checking calender

**Comment by RoseLoverX** [comment]
@AnjanaMadu Ok deer then oct 5

**Comment by AnjanaMadu** [comment]
https://github.com/AmarnathCJD/gogram/issues/45#issuecomment-1878373352
