### ISSUE TITLE
How to get an id through an invite link on a channel or group

### ISSUE THREAD

**Issue by Esiarp8** [AmarnathCJD/gogram#58]
hello, how to get an id through an invite link on a channel or group
message.ForwardTo(message.ChatID())
I would like to forward a message directly to the linked group via the link
can't seem to find it haha

**Comment by AmarnathCJD** [comment]
@Esiarp8 client.MessagesCheckChatInvite maybe 🤔

**Comment by AmarnathCJD** [comment]
@AmarnathCJD You have join private chat if u have to send message there, client.MessagesImportChatInvite
