### ISSUE TITLE
Still the same problem as before, MessagesCheckChatInvite

### ISSUE THREAD

**Issue by Esiarp8** [AmarnathCJD/gogram#59]
hello, I tried to use this to get the chat ID but got an address, 0xc0162379a0
This type *telegram.ChatInvite
How do I get what's in the address?
inviteLinkInfo, _ := client.MessagesCheckChatInvite(inviteLink)

**Comment by AmarnathCJD** [comment]
That's basic golang
link := inviteLinkInfo.(*telegram.ChatInviteObj)

**Comment by Esiarp8** [comment]
What I get is the type of ChatInviteAlready, but only the
&{0xc01b8365a0}
How to get the same as below
(chatInviteAlready (ID: 0x5abcdefg) = (chat=(channel (ID: 0x5abcdefg) = (creator=None, kicked=None, left=None, editor=True, moderator=None, broadcast=True, verified=None, megagroup=None, restricted=None, democracy=None, signatures=None, min=None, id=123456789, access_hash=615xxxxxxxxx, title=testChannel, username=None, photo=(chatPhotoEmpty (ID: 0x37xxxxxxx) = ()), date=2017-06-14 14:34:50, version=0, restriction_reason=None))))

**Comment by AmarnathCJD** [comment]
chatInviteAlready.Chat.(*telegram.Channel)

**Comment by Esiarp8** [comment]
> chatInviteAlready.Chat.(*telegram.ChannelObj)
thank you haha
