### ISSUE TITLE
Need a little more help

### ISSUE THREAD

**Issue by Esiarp8** [AmarnathCJD/gogram#60]
inviteLinkInfo, err := client.MessagesCheckChatInvite(inviteLink_ID)
obj, _:=inviteLinkInfo.(*telegram.ChatInviteObj)   //field Participants []telegram.User
obj.Participants     //How to get the actual content, not the address

update_afterjoin,_:=client.MessagesImportChatInvite(inviteLink_ID)
type UpdatesObj struct {
    Updates []Update
    Users   []User
    Chats   []Chat
    Date    int32
    Seq     int32
}
update_afterjoin.(*telegram.UpdatesObj).Chats  
 //How to get the actual content, not the address
 [0xc0082787e0 0xc008278a80 0xc008278d20]

**Comment by AmarnathCJD** [comment]
Assert type again in for loop

For example
for _, v := range update_afterjoin.(*telegram.UpdatesObj).Chats {
 if c, ok := v.(*telegram.ChannelObj"); ok {
    // c.Username
 } // else *telegram.ChatObj.....

**Comment by Esiarp8** [comment]
really thank you haha
