### ISSUE TITLE
BUG with GetDialog function

### ISSUE THREAD

**Issue by niaguiar** [AmarnathCJD/gogram#62]
When I call the Get Dialogs function it generates the following error
[session](panic: sending MessagesGetDialogs: sending packet: marshaling request: value can't be nil)

[Code](https://go.dev/play/p/PUqAFtVkBiX)

**Comment by XiaolinLeo** [comment]
I had the same problem

**Comment by AmarnathCJD** [comment]
@XiaolinLeo can you try now.

**Comment by XiaolinLeo** [comment]
@AmarnathCJD Fixed, thank you
