### ISSUE TITLE
Desperately in Need of Documentation Support

### ISSUE THREAD

**Issue by Nx-117** [AmarnathCJD/gogram#66]
No need for "beautiful Docs" right now. Please just provide some documentation, even if it's a work in progress.ORZ

**Comment by AmarnathCJD** [comment]
Ok I'll look into it, but don't have the domain

**Comment by AmarnathCJD** [comment]
stop

**Comment by AmarnathCJD** [comment]
stop

**Comment by AmarnathCJD** [comment]
stop

**Comment by TAMILVIP007** [comment]
@AmarnathCJD nigga?

**Comment by AmarnathCJD** [comment]
> @AmarnathCJD nigga?

Nigga ur posy

**Comment by AmarnathCJD** [comment]
> @AmarnathCJD jnl

Not from u

**Comment by ShamanValius** [comment]
Документацию бы)) Очень не удобно лазить по коду и читать комментарии (где они есть). Благо хотя бы комментарии присутствуют.

**Comment by SantiiRepair** [comment]
🤔🤔🤔🤔
