### ISSUE TITLE
no channel with id ########## or missing from cache

### ISSUE THREAD

**Issue by jMurad** [AmarnathCJD/gogram#67]
I can't receive messages, no id found.

dialogs, err := client.GetDialogs()
if err != nil {
	panic(err)
}
for _, dialog := range dialogs {
	switch d := dialog.(type) {
	case *telegram.DialogObj:
		messages, err := client.GetMessages(d.Peer)
		if err != nil {
			panic(err)
		}
		for _, msg := range messages {
			fmt.Println("ID:", msg.ID)
		}
	}
}
panic: no channel with id ########## or missing from cache

**Comment by RoseLoverX** [comment]
@jMurad raw method don't add peer to cache, so you have to create telegram.InputPeerChannel or InputPeerChat object using the acccessHash and ID of peer then use it

**Comment by jMurad** [comment]
@RoseLoverX, how to get acccessHash?

**Comment by AmarnathCJD** [comment]
Its fixed now Try.

```go
package main

import (
	"fmt"

	"github.com/amarnathcjd/gogram/telegram"
)

func main() {
	client, err := telegram.NewClient(telegram.ClientConfig{})
	if err != nil {
		fmt.Println(err)
	}
	client.Connect()

	dialogs, _ := client.GetDialogs(&telegram.DialogOptions{
		Limit: 10,
	})
	for _, dial := range dialogs {
		dialog := dial.(*telegram.DialogObj)
		if _, err := client.SendMessage(dialog.Peer, "@TamilVip07 us Nibba"); err != nil {
			fmt.Println(err)
		}
	}
}
```

**Comment by jMurad** [comment]
How to get all messages of channel?
