### ISSUE TITLE
Why is there no response when I execute the Connect method?

### ISSUE THREAD

**Issue by wind-hx** [AmarnathCJD/gogram#79]
```
	log.Printf("init...\n")
	appID := int32(94575)
	appHash := "a3406de8d171bb422bb6ddf3bbd800e2"
	client, _ := telegram.NewClient(telegram.ClientConfig{
		AppID:         appID,
		AppHash:       appHash,
		LogLevel:      telegram.LogDebug,
		StringSession: "1BvXUXQ3ZHVBcWV2MGF5UXFCMHRYWGRORk44Zlh2Z2FJbGI1dVNzVnlRV1cyYXMxS21wVldDWTh6cFordkRUN2xjdmdiSnRpRlVLVlZVUllpRjcyRUJOS3JTYmVnc2JmR3ZhZW91TjBDYTBBQndrV25ON2ptS3FXRzE4aXBsWVNaMlJ0bUdycEtock5lcHB2RDhoM0Via0Q0cU9DRVhZRmpiUDBHOXpjczE5OHJxZklxOWxlbTRYbThsaUhNWEpJeVhmYi9QOGRKV2oybmxUS21FZFZkMWhVZ3FLKy84Lysvay9kNjlLYTA2YUlncVBWZWg4SU5pRlk1TW5LVC9sU2MrS0Vhd2JRV1YyQlo3bzRaTGx6ME1WNCtmMndmRXdoN1J6aGRxWGNlenVxUlVYbGpIWXBDdXVHclZJdUluNlpTMGVINGcrVnhacTJLdHRacm4ydTFiaTBnPT06OlF0N2R1QXFldjBheVFxQjB0WFhkTkZOOGZYdmdhSWxiNXVTc1Z5UVdXMmFzMUttcFZXQ1k4enBaK3ZEVDdsY3ZnYkp0aUZVS1ZWVVJZaUY3MkVCTktyU2JlZ3NiZkd2YWVvdU4wQ2EwQUJ3a1duTjdqbUtxV0cxOGlwbFlTWjJSdG1HcnBLaHJOZXBwdkQ4aDNFYmtENHFPQ0VYWUZqYlAwRzl6Y3MxOThycWZJcTlsZW00WG04bGlITVhKSXlYZmIvUDhkSldqMm5sVEttRWRWZDFoVWdxSysvOC8rL2svZDY5S2EwNmFJZ3FQVmVoOElOaUZZNU1uS1QvbFNjK0tFYXdiUVdWMkJaN280WkxsejBNVjQrZjJ3ZkV3aDdSemhkcVhjZXp1cVJVWGxqSFlwQ3V1R3JWSXVJbjZaUzBlSDRnK1Z4WnEyS3R0WnJuMnUxYmkwZz09Ojo5MS4xMDguNTYuMTMxOjQ0Mzo6BTo68JeFrw",
	})

	client.Connect()
	log.Printf("init end...\n")
```

```
2024/03/13 11:26:48 init...
2024/03/13 11:26:48 gogram - cache - debug - initialized cache (gogram_heVF.db) successfully
2024/03/13 11:26:48 gogram - mtproto - debug - importing Auth from stringSession...
2024/03/13 11:26:48 gogram - mtproto - info - Connecting to [91.108.56.131:443] - <TCPFull> ...
2024/03/13 11:26:48 gogram - mtproto - info - Connection to [91.108.56.131:443] - <TCPFull> established
2024/03/13 11:26:48 gogram - client - debug - sending initial invokeWithLayer request
```

**Comment by wind-hx** [comment]
The console does not print "init end..."

**Comment by RoseLoverX** [comment]
@wind-hx did you try restarting

it's happening sometimes something issue with the TCP timeout, I'll look into it

**Comment by wind-hx** [comment]
Restarting didn't solve the problem. I found out through the logs that error code 4294966892 appeared.

**Comment by wind-hx** [comment]
https://github.com/AmarnathCJD/gogram/blob/187a9aa7f593cd9b9c134de1568b4547491c755b/mtproto.go#L451

In infinite reconnection

**Comment by RoseLoverX** [comment]
@wind-hx ohhh okey

**Comment by wind-hx** [comment]
> @wind-hx ohhh okey

It is very possible that my stringsession is abnormal, but I think it is a good choice to return err when executing the connect method, rather than letting the program wait forever, because this is not a network error.

**Comment by RoseLoverX** [comment]
@wind-hx So your string session is not valid?, the 4294966892 translated baack to -404 error code, alright so I thought the 4294966892 was related to bad authkey so kept on recreating it

**Comment by TAMILVIP007** [comment]
@wind-hx Wtf is this gey shit now

**Comment by TAMILVIP007** [comment]
@TAMILVIP007 Dat was unexpected tag, blame @RoseLoverX for using trash bot

**Comment by wind-hx** [comment]
Because I am trying to read the data in SQLite to generate stringsession, it may be caused by the invalid stringsession generated, but I think the program should not be kept waiting.

**Comment by RoseLoverX** [comment]
@wind-hx did you use telegram.Session{.....}.Encode() to generate it

**Comment by wind-hx** [comment]
> @wind-hx did you use telegram.Session{.....}.Encode() to generate it

yes, It is generated through telegram.Session{...}.Encode()

**Comment by AmarnathCJD** [comment]
@wind-hx https://github.com/AmarnathCJD/gogram/commit/50297875c0cf6aa62df6647dfdd0c22676280009

**Comment by wind-hx** [comment]
Thanks for the fix
