### ISSUE TITLE
Feat: Update to layer 159

### ISSUE THREAD

**Issue by AmarnathCJD** [AmarnathCJD/gogram#8]
## TODO -:
 1. `Add support for Flags2.0 in Schema Parser`
 2. `Same to do in Decoder`
 3. `Update to layer 159`

**Comment by anonyindian** [comment]
@AmarnathCJD

**Comment by AmarnathCJD** [comment]
> milestone

Hmm?

**Comment by anonyindian** [comment]
@anonyindian what

**Comment by AmarnathCJD** [comment]
@anonyindian ETA Nov 28

**Comment by AnjanaMadu** [comment]
@AmarnathCJD Hi

**Comment by AnjanaMadu** [comment]
@AnjanaMadu

**Comment by itzrexmodz** [comment]
@AmarnathCJD Hemlo

**Comment by AmarnathCJD** [comment]
@itzrexmodz Gmra

**Comment by itzrexmodz** [comment]
@itzrexmodz Lumd choomse🥺

**Comment by AmarnathCJD** [comment]
@itzrexmodz Be professional aka smd

**Comment by AnjanaMadu** [comment]
@AmarnathCJD Hi whores

**Comment by AmarnathCJD** [comment]
@AnjanaMadu Hi Lesbain

**Comment by AnjanaMadu** [comment]
@AmarnathCJD Our accs will get flagged soon

**Comment by itzrexmodz** [comment]
@AmarnathCJD Me pro af thats why your sister with me 😎💁‍♀

**Comment by AmarnathCJD** [comment]
@AmarnathCJD Wtf 8th issue

**Comment by AnjanaMadu** [comment]
@AmarnathCJD Lmao detele these

**Comment by AnjanaMadu** [comment]
@AnjanaMadu 🥲

**Comment by itzrexmodz** [comment]
@AnjanaMadu Hemlo deer

**Comment by TAMILVIP007** [comment]
acha

**Comment by AmarnathCJD** [comment]
@TAMILVIP007 Haan bring Dev's me buzy af

**Comment by AmarnathCJD** [comment]
To be updated on v3 release soon

**Comment by TAMILVIP007** [comment]
soon == never.

**Comment by AmarnathCJD** [comment]
Done Finally:)
