### ISSUE TITLE
StringSession Encode、Decode,Wrong appid

### ISSUE THREAD

**Issue by wind-hx** [AmarnathCJD/gogram#83]
<img width="1282" alt="image" src="https://github.com/AmarnathCJD/gogram/assets/17685971/99f732e4-d1a9-449d-a578-d59cbe0d3cc2">
I want to export the session string and store it to redis, an incorrect appid error occurred while restoring the session by reading the redis session string, I checked the process of generating the session string through debug and found that there was a problem with the encoding format of the appid. There may be a problem that Unicode cannot be mapped, resulting in the inability to restore the session normally.

https://github.com/AmarnathCJD/gogram/blob/1391dedf69dbfda3874c9540a2a41c365307e317/internal/session/string.go#L59

```
import "strconv"

// Encode dcID and appID in Encode method
sessionContents := []string{
    string(s.authKey),
    string(s.authKeyHash),
    s.ipAddr,
    strconv.Itoa(s.dcID), // Convert int to string
    strconv.FormatInt(int64(s.appID), 10), // Convert int32 to string
}

// Decode dcID and appID in Decode method
for i, v := range split {
    switch i {
    // ... other case...
    case 3:
        dcID, err := strconv.Atoi(v) // Convert string to int
        if err != nil {
            return err
        }
        s.dcID = dcID
    case 4:
        appID, err := strconv.ParseInt(v, 10, 32) // Convert string to int64 and then to int32

        if err != nil {
            return err
        }
        s.appID = int32(appID)
    }
}
```

**Comment by AmarnathCJD** [comment]
Wouldn't it be easier to store it as the whole StringSession string 🫡

**Comment by wind-hx** [comment]
> Wouldn't it be easier to store it as the whole StringSession string 🫡

I just use string session

**Comment by wind-hx** [comment]
> Wouldn't it be easier to store it as the whole StringSession string 🫡

```
package main

import (
	"log"

	"github.com/amarnathcjd/gogram/telegram"
)

func main() {
	// CreateStringSession()
	LoadStringSession("1BvXLqqJFambVsr3ke6N1gB3lC5zvWYefUMjl2pUon70_XggcE0yEYZp-CrVIeESRgFIlTkLOs_b9a4VYty6mxh7hXnIIJyeqjyltPZ7TGVDtqHYFgE_Rm1KYRfLW3Bmwxm6KkQii47hWRugvv_RHAQIfaosWwquprc28LTJkZWUkVROZIbJ1I48xC5cbx-cfY4aiQPgN7GKswVGCEEsTK1DJTHVYEk1jaYZ-cZRno2Luil-URsN9s028WKdImT8HKIifXoeeK-0EHAsCDKuXV1Slkw7tP3qf4PYa1xzakKlvo3q17-CtuitbtJ6nP3Unng-urgyCuBcaelLnDX3pFzT6zo6ytqgXWtdrAA6OjkxLjEwOC41Ni4xNTE6NDQzOjoFOjrgp4A")
}

func LoadStringSession(session string) {
	client, err := telegram.NewClient(telegram.ClientConfig{
		AppID:         int32(2496),
		AppHash:       "8da85b0d5bfe62527e5b244c209159c3",
		LogLevel:      telegram.LogDebug,
		LangCode:      "en",
		MemorySession: true,
		StringSession: session,
	})
	if err != nil {
		log.Println(err)
		return
	}
	if !client.IsConnected() {
		client.Connect()
	}
	hash, err := client.SendCode("+1 8305073314")
	if err != nil {
		log.Println(err)
		return
	}
	log.Println(hash)
	log.Println(client.ExportSession())
}

func CreateStringSession() string {
	client, err := telegram.NewClient(telegram.ClientConfig{
		AppID:         int32(2496),
		AppHash:       "8da85b0d5bfe62527e5b244c209159c3",
		LogLevel:      telegram.LogDebug,
		LangCode:      "en",
		MemorySession: true,
	})
	if err != nil {
		log.Println(err)
		return ""
	}
	if !client.IsConnected() {
		client.Connect()
	}
	hash, err := client.SendCode("+1 8305073314")
	if err != nil {
		log.Println(err)
		return ""
	}
	log.Println(hash)
	return client.ExportSession()
}

```
When the exported Session passes the LoadStringSession method, [API_ID_INVALID] API ID invalid. (code 400) will appear.

**Comment by AmarnathCJD** [comment]
I'll check

**Comment by wind-hx** [comment]
> I'll check

The test code I provided, the execution result is [API_ID_INVALID] API ID invalid. (code 400), What is the result of executing the same code?

**Comment by AmarnathCJD** [comment]
> > I'll check
> 
> The test code I provided, the execution result is [API_ID_INVALID] API ID invalid. (code 400), What is the result of executing the same code?

int32(2496),

did you change this value for posting here?

obviosly otherwise its invalid.

**Comment by AmarnathCJD** [comment]
https://github.com/AmarnathCJD/gogram/commit/2127995d66f8d635899d5e3ba5f4ac9a7355c89b
