### ISSUE TITLE
..

### ISSUE THREAD

**Issue by satyajitgiram** [AmarnathCJD/gogram#93]
..

**Comment by satyajitgiram** [comment]
If you report me then you are very much gay just delete this repo or else I fuck you very hard until you cry

**Comment by TAMILVIP007** [comment]
@satyajitgiram lmfao

**Comment by satyajitgiram** [comment]
@TAMILVIP007 delete this repo and don't tag me

**Comment by TAMILVIP007** [comment]
@satyajitgiram lmfao

**Comment by TAMILVIP007** [comment]
@satyajitgiram lmfao

**Comment by TAMILVIP007** [comment]
@satyajitgiram lmfao

**Comment by TAMILVIP007** [comment]
@satyajitgiram lmfao

**Comment by TAMILVIP007** [comment]
@satyajitgiram lmfao

**Comment by TAMILVIP007** [comment]
@satyajitgiram lmfao

**Comment by TAMILVIP007** [comment]
@satyajitgiram lmfao

**Comment by TAMILVIP007** [comment]
@satyajitgiram lmfao

**Comment by RoseLoverX** [comment]
@satyajitgiram Lmfaoo

**Comment by RoseLoverX** [comment]
@RoseLoverX which repo is this
