### ISSUE TITLE
Hello, cant find an easy way to disable cache or to set an expiration time, im required to get the channel ParticipantsCount every hour, but cache is hitting the same result

### ISSUE THREAD

**Issue by ramses3** [AmarnathCJD/gogram#98]
**Is your feature request related to a problem? Please describe.**
Cant find an easy way to disable cache or to set an expiration time, im required to get the channel ParticipantsCount every hour, but cache is hitting the same result

**Describe the solution you'd like**
Somewhere to set a cache enable/disable option

**Describe alternatives you've considered**
Avoid cache at all

**Comment by AmarnathCJD** [comment]
what do you mean by cache on participant count

cache only stores the channel id+access_hash

_, count, _ := client.GetChatMembers(chatId, &ParticipantOptions{Limit: 0})

is independent of the caching system

if you wanna manipulate the cache:

client.Cache.ImportJSON, edit as required 

or to disable cache

telegram.NewClient(telegram.ClientConfig{
DisableCache: true,
})

if not solved share the code and little more details.

**Comment by AmarnathCJD** [comment]
@ramses3 channel.PqrticupantCount is always 0

use ChannelsGetParticipants request with limit as 0 to get the count.

or GetFullChannelRequest

**Comment by ramses3** [comment]
@AmarnathCJD Seems it require admin rights to call ChannelsGetParticipants ?, i just need the participant count, like on the app as normal user

**Comment by AmarnathCJD** [comment]
> @AmarnathCJD Seems it require admin rights to call ChannelsGetParticipants ?, i just need the participant count, like on the app as normal user

GetFullChannelRequest
